# Generated by Django 6.0.4 on 2026-04-16 04:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fairy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("runtime", models.CharField(max_length=32)),
                ("prompt", models.TextField()),
                ("sprite_name", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("exit_code", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "agent_sessions",
            },
        ),
        migrations.AlterField(
            model_name="userruntimekey",
            name="runtime",
            field=models.CharField(
                choices=[
                    ("claude", "claude"),
                    ("codex", "codex"),
                    ("gemini", "gemini"),
                    ("claude-oauth", "claude-oauth"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="AgentSessionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stream",
                    models.CharField(
                        choices=[("stdout", "stdout"), ("stderr", "stderr")],
                        max_length=6,
                    ),
                ),
                ("data", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="fairy.agentsession",
                    ),
                ),
            ],
            options={
                "db_table": "agent_session_logs",
                "indexes": [
                    models.Index(
                        fields=["session", "id"], name="agent_sessi_session_049341_idx"
                    )
                ],
            },
        ),
    ]
