# Generated by Django 5.2.13 on 2026-04-16 06:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fairy", "0004_add_session_resource"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("terminated", "Terminated"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("system", models.TextField(blank=True, default="")),
                ("model", models.CharField(max_length=100)),
                (
                    "runtime",
                    models.CharField(
                        choices=[
                            ("claude", "claude"),
                            ("codex", "codex"),
                            ("gemini", "gemini"),
                            ("claude-oauth", "claude-oauth"),
                        ],
                        max_length=32,
                    ),
                ),
                ("skills", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "agents",
            },
        ),
        migrations.AddField(
            model_name="agentsession",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sessions",
                to="fairy.agent",
            ),
        ),
        migrations.CreateModel(
            name="AgentVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("system", models.TextField(blank=True, default="")),
                ("model", models.CharField(max_length=100)),
                ("runtime", models.CharField(max_length=32)),
                ("skills", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="fairy.agent",
                    ),
                ),
            ],
            options={
                "db_table": "agent_versions",
                "ordering": ["-version"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("agent", "version"), name="unique_agent_version"
                    )
                ],
            },
        ),
    ]
