# Generated by Django 5.2.13 on 2026-04-16 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fairy", "0005_add_agent_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="model",
            field=models.CharField(
                choices=[
                    ("claude-opus-4-6", "claude-opus-4-6"),
                    ("claude-sonnet-4-6", "claude-sonnet-4-6"),
                    ("claude-haiku-4-5", "claude-haiku-4-5"),
                    ("claude-opus-4-0-20250514", "claude-opus-4-0-20250514"),
                    ("claude-sonnet-4-0-20250514", "claude-sonnet-4-0-20250514"),
                    ("claude-sonnet-4-5-20250514", "claude-sonnet-4-5-20250514"),
                    ("claude-3-5-haiku-20241022", "claude-3-5-haiku-20241022"),
                    ("gpt-4.1", "gpt-4.1"),
                    ("o3", "o3"),
                    ("o4-mini", "o4-mini"),
                    ("gemini-2.5-pro", "gemini-2.5-pro"),
                    ("gemini-2.5-flash", "gemini-2.5-flash"),
                ],
                max_length=100,
            ),
        ),
    ]
