# Generated by Django 6.0.4 on 2026-04-16 06:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fairy", "0006_agent_model_choices"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Environment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("packages", models.JSONField(blank=True, default=dict)),
                ("env_vars", models.JSONField(blank=True, default=dict)),
                ("setup_script", models.TextField(blank=True, default="")),
                (
                    "networking_type",
                    models.CharField(
                        choices=[
                            ("unrestricted", "Unrestricted"),
                            ("limited", "Limited"),
                        ],
                        default="unrestricted",
                        max_length=16,
                    ),
                ),
                ("networking_config", models.JSONField(blank=True, default=dict)),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="environments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "environments",
            },
        ),
        migrations.AddField(
            model_name="agent",
            name="environment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agents",
                to="fairy.environment",
            ),
        ),
        migrations.AddField(
            model_name="agentsession",
            name="environment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sessions",
                to="fairy.environment",
            ),
        ),
        migrations.AddField(
            model_name="agentversion",
            name="environment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="fairy.environment",
            ),
        ),
        migrations.CreateModel(
            name="EnvironmentVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=200)),
                ("packages", models.JSONField(blank=True, default=dict)),
                ("env_vars", models.JSONField(blank=True, default=dict)),
                ("setup_script", models.TextField(blank=True, default="")),
                ("networking_type", models.CharField(max_length=16)),
                ("networking_config", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "environment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="fairy.environment",
                    ),
                ),
            ],
            options={
                "db_table": "environment_versions",
                "ordering": ["-version"],
            },
        ),
        migrations.AddConstraint(
            model_name="environment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("archived_at__isnull", True)),
                fields=("user", "name"),
                name="unique_active_environment_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="environmentversion",
            constraint=models.UniqueConstraint(
                fields=("environment", "version"), name="unique_environment_version"
            ),
        ),
    ]
