# Generated by Django 6.0.4 on 2026-04-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fairy", "0007_environment_agent_environment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="mcp_servers",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="agent",
            name="tools",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="agentversion",
            name="mcp_servers",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="agentversion",
            name="tools",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
