# Generated by Django 5.2.13 on 2026-04-16 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fairy", "0003_agentsession_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[("github_repository", "GitHub Repository")],
                        max_length=32,
                    ),
                ),
                ("url", models.URLField(max_length=500)),
                ("mount_path", models.CharField(max_length=500)),
                ("encrypted_token", models.BinaryField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="fairy.agentsession",
                    ),
                ),
            ],
            options={
                "db_table": "session_resources",
            },
        ),
    ]
