# Generated by Django 6.0.4 on 2026-04-17 12:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fairy", "0008_add_tools_mcp_servers_to_agent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agent",
            name="tools",
        ),
        migrations.RemoveField(
            model_name="agentversion",
            name="tools",
        ),
    ]
