# Generated by Django 6.0.4 on 2026-04-19 01:43

import django.db.models.deletion
from django.db import migrations, models


def backfill_turn_one(apps, schema_editor):
    """Create a synthetic turn 1 for every existing session and attach its logs.

    Maps the legacy session.status to a terminal turn status where possible:
    running/pending → pending, completed → completed, failed/terminated → failed.
    """
    AgentSession = apps.get_model("fairy", "AgentSession")
    SessionTurn = apps.get_model("fairy", "SessionTurn")
    AgentSessionLog = apps.get_model("fairy", "AgentSessionLog")

    status_map = {
        "pending": "pending",
        "running": "running",
        "completed": "completed",
        "failed": "failed",
        "terminated": "failed",
    }

    for session in AgentSession.objects.all().iterator():
        turn = SessionTurn.objects.create(
            session=session,
            turn_number=1,
            prompt=session.prompt,
            status=status_map.get(session.status, "failed"),
            exit_code=session.exit_code,
            created_at=session.created_at,
            started_at=session.created_at,
            ended_at=session.updated_at if session.status not in ("pending", "running") else None,
        )
        AgentSessionLog.objects.filter(session=session, turn__isnull=True).update(turn=turn)


class Migration(migrations.Migration):

    dependencies = [
        ("fairy", "0010_userspriteskey"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionTurn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("turn_number", models.PositiveIntegerField()),
                ("prompt", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("exit_code", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turns",
                        to="fairy.agentsession",
                    ),
                ),
            ],
            options={
                "db_table": "session_turns",
                "ordering": ["session", "turn_number"],
            },
        ),
        migrations.AddField(
            model_name="agentsessionlog",
            name="turn",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="fairy.sessionturn",
            ),
        ),
        migrations.AddIndex(
            model_name="agentsessionlog",
            index=models.Index(
                fields=["turn", "id"], name="agent_sessi_turn_id_c5c936_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="sessionturn",
            constraint=models.UniqueConstraint(
                fields=("session", "turn_number"), name="unique_session_turn_number"
            ),
        ),
        migrations.RunPython(backfill_turn_one, migrations.RunPython.noop),
    ]
