# Generated by Django 6.0.4 on 2026-04-19 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fairy", "0011_add_session_turns"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentsession",
            name="runtime_session_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
