# Generated by Django 6.0.4 on 2026-04-22 03:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fairy", "0013_userquota"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentsessionlog",
            name="duration_ms",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agentsessionlog",
            name="kind",
            field=models.CharField(
                choices=[("output", "output"), ("stage", "stage")],
                default="output",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="agentsessionlog",
            name="stage",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="agentsessionlog",
            name="state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("started", "started"),
                    ("done", "done"),
                    ("failed", "failed"),
                ],
                default="",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="agentsessionlog",
            name="data",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="agentsessionlog",
            name="stream",
            field=models.CharField(
                blank=True,
                choices=[("stdout", "stdout"), ("stderr", "stderr")],
                default="",
                max_length=6,
            ),
        ),
    ]
