"""
Hand-crafted mock research findings for Brief demo targets.
Each target has findings across 4 dimensions, written to feel like
real concurrent agent research output.
"""

DIMENSIONS = [
    "product_positioning",
    "team_history",
    "customers_market",
    "competitors_landscape",
]

DIMENSION_LABELS = {
    "product_positioning": "Product & Positioning",
    "team_history": "Team & History",
    "customers_market": "Customers & Market",
    "competitors_landscape": "Competitors & Landscape",
}

RESEARCH_DATA = {
    "Linear": {
        "product_positioning": [
            "Researching Linear's product positioning...",
            "Found: Issue tracker and project management built for modern software teams",
            "Core insight: Speed is the primary differentiator — keyboard-first UI, optimistic updates make it feel instant",
            "Architecture: Fully local-first sync engine (Linear Sync Engine, open-sourced 2023)",
            "Pricing: Free (up to 250 issues), Team $8/seat/mo, Business $16/seat/mo, Enterprise custom",
            "Key features: Issues, Cycles (sprints), Projects, Roadmaps, Linear Asks, Linear Insights",
            "Recent launches: Linear Asks (async Q&A across Slack), Linear Insights (analytics), AI-assisted issue creation",
            "Positioning vs Jira: 'built for speed, not for enterprise bureaucracy'",
            "Positioning vs GitHub Issues: more structure, roadmaps, cross-repo views",
            "Positioning vs Notion: purpose-built for engineering, not a general workspace",
            "Brand voice: opinionated, tasteful, developer-adjacent — no marketing fluff",
            "Notable: Linear's own changelog/blog is a product demo in itself — impeccable design",
        ],
        "team_history": [
            "Researching Linear's team and founding story...",
            "Founded: 2019 by Karri Saarinen (CEO), Jori Lallo (CTO), Tuomas Artman (CTO)",
            "All three founders previously worked at Coinbase and Airbnb",
            "Karri Saarinen: former principal designer at Airbnb, drove design systems work",
            "Origin story: frustration with Jira while building products at scale",
            "First version built in ~6 weeks, launched to a waiting list in late 2019",
            "Funding: Seed from Index Ventures (~2020), Series A $35M from Accel (2021)",
            "Series B $50M led by Thrive Capital (2022) — valuation ~$400M",
            "Team size: ~60 people as of 2024, intentionally small and high-density",
            "Engineering culture: strong opinions on craft — Linear's design docs are legendary internally",
            "Remote-first but has offices in San Francisco and Helsinki",
            "Notable hire: recruited heavily from Figma, Stripe, Vercel ecosystem",
            "Philosophy: 'Build like the early internet' — ship fast, keep it simple, trust your taste",
        ],
        "customers_market": [
            "Researching Linear's customers and market position...",
            "Primary customer: software engineering teams at high-growth startups and scale-ups",
            "Sweet spot: Series A to Series C companies, 10–500 engineers",
            "Notable customers: OpenAI, Vercel, Ramp, Retool, Mercury, Loom, Raycast",
            "Customer acquisition: strong bottoms-up / PLG motion — engineers adopt, then teams pay",
            "Expansion: land with one team, expand to whole engineering org",
            "NPS: reported to be exceptionally high — Linear has vocal evangelists on Twitter/X",
            "Market size: project management software TAM ~$6.5B, growing ~12% YoY",
            "ICP signal: companies that care deeply about engineering culture and tooling quality",
            "Geographic split: primarily US (60%), Europe (30%), rest of world (10%)",
            "ARR: not disclosed, estimated $30–50M ARR based on funding and team size signals",
            "Growth: reported 3x YoY in 2022, slowing to ~2x in 2023 as base grows",
            "Retention: very high — Linear switching costs are low technically but high culturally",
        ],
        "competitors_landscape": [
            "Researching Linear's competitive landscape...",
            "Primary competitor: Atlassian Jira — dominant incumbent, ~$4B ARR, enterprise-heavy",
            "Jira weakness: slow, bloated, UI hasn't kept pace with modern dev tooling expectations",
            "GitHub Issues: free, integrated with code — wins for OSS and GitHub-native teams",
            "Shortcut (formerly Clubhouse): similar PLG/startup positioning, smaller scale",
            "Notion: teams use it for lightweight project tracking, but Linear is more structured",
            "Asana/Monday.com: more PM-focused, less engineering-native",
            "Height: well-designed alternative, smaller team and community",
            "Emerging threat: GitHub Projects has improved significantly (2022-2024)",
            "Emerging threat: Cursor/AI-native tools may redefine how issues are tracked",
            "Linear's moat: brand, community, UX quality — hard to replicate quickly",
            "Competitive dynamic: Linear is taking market share from Jira at the startup end",
            "Risk: if Jira modernizes (Atlassian has been trying), premium positioning narrows",
            "Opportunity: enterprise upmarket move — Linear for Business is gaining traction",
        ],
    },
    "Resend": {
        "product_positioning": [
            "Researching Resend's product positioning...",
            "Found: Email API for developers — positioned as 'the email service built by developers, for developers'",
            "Core product: Transactional email API with a React Email integration as key differentiator",
            "React Email: open-source library for building email templates with React components",
            "This is the wedge — React Email (free, OSS) → Resend (paid sending infrastructure)",
            "Pricing: Free (3,000 emails/mo, 1 domain), Pro $20/mo (50K emails), Scale $90/mo (100K)",
            "Key features: Email API, React Email templates, webhooks, logs, analytics, domains",
            "Recent: Launched Broadcasts (bulk email/newsletters), Audiences (contact management)",
            "Moving from transactional-only to full email platform — competing upmarket",
            "DX obsession: API designed to feel like Stripe — clean, predictable, great docs",
            "Brand: minimalist, dark mode, developer-first — fits perfectly in the modern dev stack",
            "Integration story: works with Next.js, Vercel, Supabase, PlanetScale — the modern stack",
        ],
        "team_history": [
            "Researching Resend's founding team and history...",
            "Founded: 2023 by Zeno Rocha (CEO) and Bu Kinoshita (CTO)",
            "Zeno Rocha: prolific OSS contributor, creator of dracula theme (millions of installs), former VP of DX at WorkOS",
            "Bu Kinoshita: previously at Facebook/Meta infrastructure, email systems background",
            "Origin: Zeno built React Email as a side project, realized the sending layer was also broken",
            "YC W23 batch — raised seed during YC, launched publicly March 2023",
            "Funding: YC + seed round from notable angels including Paul Copplestone (Supabase), Guillermo Rauch (Vercel)",
            "Series A: $5M led by SV Angel (2023) — lean raise, profitable trajectory",
            "Team: ~15 people as of 2024, fully remote",
            "OSS DNA: Zeno's personal brand and OSS reputation drove early adoption massively",
            "React Email repo: 12,000+ GitHub stars within first year — organic developer distribution",
            "Culture: ship fast, write great docs, treat developers as the customer",
        ],
        "customers_market": [
            "Researching Resend's customer base and market...",
            "Primary customer: developers building SaaS apps, indie hackers, startup engineering teams",
            "Entry point: often starts as 'just need to send a welcome email' and expands",
            "Notable customers: Supabase uses Resend, Vercel ecosystem companies, thousands of indie apps",
            "Strength: extremely easy to get started — working email in 10 minutes from signup",
            "Market: transactional email TAM ~$1.5B, but adjacent to broader email/communication market",
            "Real TAM: email API + email marketing combined is $5B+ and growing",
            "Growth driver: every new SaaS app needs email — and new SaaS apps are being built faster than ever",
            "PLG motion: free tier is very generous, credit card not required — low friction",
            "Expansion: customers grow with their product — email volume scales with user base",
            "Geographic: global but US-heavy, strong in the Next.js/Vercel developer community",
            "Community: active Discord, high Twitter/X presence — developers share Resend setups publicly",
            "Churn risk: low on infrastructure layer — email is critical path, rarely switched once embedded",
        ],
        "competitors_landscape": [
            "Researching Resend's competitive landscape...",
            "Incumbent #1: SendGrid (Twilio) — massive scale, complex API, dated DX, enterprise-focused",
            "Incumbent #2: Mailgun — developer-friendly historically, but Sinch acquisition dampened momentum",
            "Incumbent #3: Postmark — good DX, transactional only, small team, niche positioning",
            "AWS SES: cheap but painful to set up, no React integration, poor deliverability tooling",
            "Brevo (ex-Sendinblue): European player, more marketing email focus",
            "Loops.so: competing for the 'email for SaaS' space, more CRM/lifecycle angle",
            "Customer.io: marketing automation, upmarket from Resend's ICP",
            "Resend's advantage: React Email moat — no competitor has an equivalent OSS project",
            "Resend's advantage: brand and DX — developers genuinely enjoy using it",
            "Risk: SendGrid/Mailgun could ship a React Email integration and close the gap",
            "Risk: Vercel could acquire or build email sending natively into their platform",
            "Opportunity: Broadcasts/Audiences expansion into marketing email is a large adjacent market",
            "Strategic position: currently occupying 'the cool new email API' — needs to grow before incumbents react",
        ],
    },
    "Fly.io": {
        "product_positioning": [
            "Researching Fly.io's product positioning...",
            "Found: Application deployment platform — 'deploy your app close to your users, globally'",
            "Core concept: Firecracker microVMs running in 35+ regions worldwide — not containers on a hyperscaler",
            "Key differentiator: run full VMs (not just functions) at the edge with persistent state",
            "Postgres anywhere: Fly Postgres is a first-class citizen — distributed, close to compute",
            "Pricing: pay-per-resource, no seat pricing — developer-centric model",
            "Free allowance: generous — 3 shared VMs, 3GB storage, 160GB outbound transfer/mo",
            "Key products: Fly Machines (VMs), Fly Postgres, Fly Redis (Upstash), Tigris (S3-compatible storage)",
            "Recent: Fly GPUs launched — run ML workloads on A100s globally, same deploy workflow",
            "Positioning vs Heroku: 'Heroku but modern and actually fast'",
            "Positioning vs Render: more control, more global, more powerful primitives",
            "Positioning vs AWS/GCP: dramatically simpler, opinionated, developer-first",
            "Tagline energy: 'run your full-stack app globally without becoming a DevOps engineer'",
        ],
        "team_history": [
            "Researching Fly.io's team and company history...",
            "Founded: 2017 by Kurt Mackey (CEO) and Jerome Gravel-Niquet",
            "Pre-Fly: Kurt ran Appoxy (acquired by Amazon, became part of Elastic Beanstalk) and IronWorker",
            "Long background in distributed systems and application hosting infrastructure",
            "Initial product: actually started as a CDN/edge proxy for legacy apps — pivoted to full app platform",
            "Funding: bootstrapped for years, then raised $70M Series B in 2022 led by NEA",
            "Total raised: ~$75M — relatively lean for the infrastructure scale they operate",
            "Team: ~100 people, fully remote — distributed across US, Europe, Australia",
            "Culture: extremely technical, low tolerance for BS, strong opinions on infrastructure design",
            "Blog: Fly's technical blog is one of the best in infrastructure — deeply technical, honest",
            "Open source: Fly builds on and contributes to Firecracker, open-sources tooling",
            "Notable: Kurt is extremely online and very direct — has shaped the brand's voice significantly",
            "2023 challenge: grew very fast, faced reliability issues, addressed them publicly and directly",
        ],
        "customers_market": [
            "Researching Fly.io's customer base and market...",
            "Primary customer: developers who've outgrown simple hosting but don't want AWS complexity",
            "Strong in: Rails apps, Elixir/Phoenix (Kurt has Elixir background), Django, Node",
            "Specific ICP: engineering teams at seed-to-Series B companies, technical founders",
            "Notable use cases: running LLM inference endpoints, real-time collaboration apps, global SaaS",
            "Community: very active forum (community.fly.io), high engagement, technically sophisticated users",
            "Market: cloud infrastructure TAM is enormous ($500B+) but Fly targets a specific layer",
            "Relevant TAM: PaaS / developer cloud segment — ~$10B, growing as devs flee hyperscaler complexity",
            "Geographic: global by nature of the product — strong US and European developer communities",
            "GPU compute angle: new market for ML teams that want simpler GPU orchestration than raw cloud",
            "Expansion signal: customers start with one app, deploy more as trust builds",
            "Pricing dynamic: usage-based means customers grow spend naturally without upsell friction",
            "Risk segment: customers leave when they need something very custom or have GCP/AWS requirements",
        ],
        "competitors_landscape": [
            "Researching Fly.io's competitive landscape...",
            "Render: closest competitor in developer experience and positioning — simpler, less powerful",
            "Railway: newer, beautiful UX, growing fast among indie developers and small teams",
            "Heroku: the original PaaS — still has brand recognition, dramatically declined post-Salesforce",
            "Heroku 2024: now owned by Salesforce, finally re-introduced free tier, but trust is damaged",
            "AWS App Runner / Elastic Beanstalk: exist but complex, feel like afterthoughts",
            "Google Cloud Run: serverless containers, strong competitor for stateless workloads",
            "Coolify: open-source self-hosted alternative — growing, appeals to cost-sensitive users",
            "Vercel/Netlify: front-end/serverless focused — different layer but compete for developer mindshare",
            "Modal: strong competitor for GPU/ML workloads specifically",
            "Fly's moat: global VM primitives — no other PaaS runs real VMs in as many regions with persistent storage",
            "Fly's moat: Firecracker-based architecture enables things competitors can't do at their layer",
            "Risk: Railway and Render improving rapidly — DX gap is closing",
            "Risk: AWS/GCP could ship a dramatically simpler product and use distribution advantage",
            "Opportunity: GPU compute is wide open — very few players combine ease-of-use with GPU access globally",
        ],
    },
}

SYNTHESIS_DATA = {
    "Linear": {
        "summary": "Linear is a high-conviction bet on developer taste as a competitive moat. The company has built the project management tool that modern engineering teams actually want to use — fast, opinionated, and beautifully designed. After 5 years, it has achieved strong product-market fit with high-growth startups and is beginning to move upmarket.",
        "key_themes": [
            "Speed and craft as the core product identity — not just a feature but a philosophy",
            "Bottom-up PLG motion driven by strong engineer advocacy",
            "Intentionally small team (~60 people) operating with high efficiency",
            "Strong brand in the developer-adjacent community creates organic distribution",
        ],
        "risks": [
            "GitHub Projects has significantly improved — the free+integrated alternative is getting stronger",
            "Enterprise upmarket move requires sales motion the team hasn't had to build before",
            "Reliance on startup market means sensitive to funding environment slowdowns",
        ],
        "opportunities": [
            "Linear for Business / Enterprise is early and underpenetrated",
            "AI integration (Linear Asks, AI issue creation) could accelerate the workflow further",
            "International expansion — strong US base but European market is underdeveloped",
        ],
        "open_questions": [
            "What is the actual ARR and growth rate as of 2024?",
            "Is the enterprise motion working — what's the ACV for enterprise deals?",
            "How does Linear think about the GitHub Projects threat specifically?",
            "Is the founding team open to additional funding or exploring strategic options?",
        ],
    },
    "Resend": {
        "summary": "Resend has executed a textbook OSS-led developer GTM: build a beloved open-source project (React Email), use it to acquire developers, then monetize the infrastructure layer. In 18 months they've gone from zero to a meaningful email API business with strong retention characteristics. The platform expansion into Broadcasts suggests ambition beyond transactional email.",
        "key_themes": [
            "React Email as OSS distribution moat — generates organic top-of-funnel at scale",
            "Founder's personal brand (Zeno Rocha) is an underrated growth asset",
            "DX-first positioning resonates strongly in the Vercel/Next.js ecosystem",
            "Very lean team operating at impressive scale — capital efficient by design",
        ],
        "risks": [
            "Incumbents (SendGrid, Mailgun) could ship React Email integrations and close the DX gap",
            "Vercel partnership is a strength but also a concentration risk",
            "Moving upmarket into Broadcasts/marketing email means competing with well-funded players",
        ],
        "opportunities": [
            "Broadcasts + Audiences expansion creates a full email platform play",
            "React Email is embedded in millions of codebases — ongoing distribution advantage",
            "International developer communities are growing rapidly — underserved by current players",
        ],
        "open_questions": [
            "What is current MRR and growth trajectory?",
            "How sticky are Broadcasts customers vs. transactional-only customers?",
            "Is Zeno planning to raise a larger round to fund the platform expansion?",
            "What's the deliverability infrastructure — own IPs or leveraging a third-party?",
        ],
    },
    "Fly.io": {
        "summary": "Fly.io is building a genuinely differentiated infrastructure layer — real VMs, globally distributed, with a developer experience that abstracts away the complexity. The GPU compute expansion is strategically smart: it applies the same 'powerful primitives, simple interface' formula to the fastest-growing infrastructure market. The company has had reliability challenges but has addressed them with unusual transparency.",
        "key_themes": [
            "Firecracker-based VM architecture creates real technical differentiation vs. container-based competitors",
            "Global-by-default positioning is increasingly relevant as apps need to be close to users",
            "GPU compute expansion opens a massive adjacent market with similar ICP",
            "Technical blog and community are genuinely excellent — underrated distribution assets",
        ],
        "risks": [
            "Railway and Render are improving fast — developer experience gap is closing",
            "2023 reliability incidents created some trust damage in the community",
            "Infrastructure businesses are capital intensive — $75M may not be enough for the ambition",
        ],
        "opportunities": [
            "Fly GPUs is early in a market (distributed GPU compute) that is growing explosively",
            "Elixir/Phoenix community is loyal and growing — a strong reference community",
            "Potential to become the default for AI application backends (inference + storage, globally)",
        ],
        "open_questions": [
            "What is ARR and growth rate — and how has GPU compute contributed?",
            "Is the team considering a Series C to fund GPU infrastructure expansion?",
            "How does Fly think about the Cloudflare Workers threat (edge compute with V8 isolates)?",
            "What percentage of revenue is from GPU vs. traditional compute?",
        ],
    },
}
